[package]
name = "quadrilateral_zoo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
tuple-map = { git = "https://github.com/nwtgck/tuple-map-rust.git" }
